import Head from 'next/head'
import Navbar from '../components/header/Navbar'
import Hero from '../components/hero/Hero'

export default function Home() {
  return (
    <>
      <Head>
        <title>Ecommerce Shoes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main>
        <Hero />
        {/* Siguientes componentes de la página principal  */}
      </main>
    </>
  )
}
